// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA21w4-ro9rEqfPKv1aBmp8U-prvzOyqfg',
    appId: '1:528166397199:web:2739fdaff43762654e8a7a',
    messagingSenderId: '528166397199',
    projectId: 'project-3a626',
    authDomain: 'project-3a626.firebaseapp.com',
    databaseURL: 'https://project-3a626-default-rtdb.firebaseio.com',
    storageBucket: 'project-3a626.appspot.com',
    measurementId: 'G-Q2BGTBDGD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgGW2IQqKT1cZDaVTtJfvjlbJKJvjyX1Y',
    appId: '1:528166397199:android:bac7d949714e15454e8a7a',
    messagingSenderId: '528166397199',
    projectId: 'project-3a626',
    databaseURL: 'https://project-3a626-default-rtdb.firebaseio.com',
    storageBucket: 'project-3a626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxvXKF-GJLwJuXvDdvrONpHkVngXEWRo',
    appId: '1:528166397199:ios:421398fac7baa5a64e8a7a',
    messagingSenderId: '528166397199',
    projectId: 'project-3a626',
    databaseURL: 'https://project-3a626-default-rtdb.firebaseio.com',
    storageBucket: 'project-3a626.appspot.com',
    iosBundleId: 'com.example.neuSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxvXKF-GJLwJuXvDdvrONpHkVngXEWRo',
    appId: '1:528166397199:ios:504ea72a192ae4e14e8a7a',
    messagingSenderId: '528166397199',
    projectId: 'project-3a626',
    databaseURL: 'https://project-3a626-default-rtdb.firebaseio.com',
    storageBucket: 'project-3a626.appspot.com',
    iosBundleId: 'com.example.neuSocial.RunnerTests',
  );
}
